export const routes = {
  public: {
    home: '/',
    projects: '/projects',
    project: (slug: string) => `/projects/${slug}`,
    tools: '/tools',
    tool: (slug: string) => `/tools/${slug}`,
    knowledge: '/knowledge',
    knowledgeArticle: (slug: string) => `/knowledge/${slug}`,
    roadmaps: '/roadmaps',
    roadmap: (slug: string) => `/roadmaps/${slug}`,
    resources: '/resources',
    journey: '/journey',
    myBlock: '/my-block',
  },
  auth: {
    login: '/login',
    forgotPassword: '/forgot-password',
    authCallback: '/auth-callback',
  },
  workspace: {
    dashboard: '/dashboard',
    assistant: '/assistant',
    debug: '/debug',
    notes: '/notes',
    conversations: '/conversations',
    decisions: '/decisions',
    profile: '/profile',
    files: '/files',
    research: '/research',
  },
  ide: {
    root: '/ide',
    project: (projectId: string) => `/ide/${projectId}`,
  },
  admin: {
    dashboard: '/admin/dashboard',
    profile: '/admin/profile',
    tools: '/admin/tools',
    projects: '/admin/projects',
    knowledge: '/admin/knowledge',
    roadmaps: '/admin/roadmaps',
    resources: '/admin/resources',
    journey: '/admin/journey',
    decisions: '/admin/decisions',
    media: '/admin/media',
    aiSettings: '/admin/ai-settings',
    users: '/admin/users',
    analytics: '/admin/analytics',
  },
  api: {
    ai: '/api/ai',
    search: '/api/search',
    recommendations: '/api/recommendations',
    health: '/api/health',
    ide: {
      projects: '/api/ide/projects',
      project: (projectId: string) => `/api/ide/projects/${projectId}`,
      files: (projectId: string) => `/api/ide/projects/${projectId}/files`,
      index: (projectId: string) => `/api/ide/projects/${projectId}/index`,
      runs: '/api/ide/runs',
      run: (runId: string) => `/api/ide/runs/${runId}`,
      assistant: '/api/ide/assistant',
      actions: '/api/ide/actions',
      action: (actionId: string) => `/api/ide/actions/${actionId}`,
      agentDevices: '/api/ide/agent/devices',
      agentPair: '/api/ide/agent/pair',
      agentPoll: '/api/ide/agent/poll',
      agentReport: '/api/ide/agent/report',
    },
  },
} as const;

export type Routes = typeof routes;
